In [4]:
import pandas as pd

In [6]:
df = pd.read_excel('C:\\Users\daspr\Downloads\ROData.xlsx')

C:\Users\daspr\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [7]:
df.head()

,SNo,RO Code,RO Name,Last Data Recvd on (Date),Last Data Recvd on (Time),Last Known Mode of Commn,LAST FCC TRANSACTION DATE,LAST FCC TRANSACTION TIME,Automation Vendor,Phase,...,VSAT INTEGRATION DATE,Last Communication over VSAT,SAT STATUS,SAT DATE,SAP STATUS,Divisional Office,Divisional Office Name,State Office,SalesArea Code,SalesArea Name
0,1.0,160683.0,AUTO FUEL SERVICE CENTRE,24-06-2022,11:30:06,Other,24-06-2022,11:30:00,ATOS,VI,...,07-01-2019,04-04-2022 22:00,ACCEPTED,30-09-2019,Active,7501.0,Guwahati DO,IndianOil-AOD St OFF,E07,Shillong II RSA
1,2.0,316084.0,AJINKYARAJE PETROLEUM,24-06-2022,11:30:06,Other,24-06-2022,11:29:54,ATOS,VII,...,18-10-2019,03-11-2021 18:19,ACCEPTED,06-11-2019,Active,3203.0,Pune DO,Maharashtra SO,M97,Osmanabad RSA
2,3.0,126314.0,Kale Service Station.,24-06-2022,11:30:06,Other,24-06-2022,11:30:00,ATOS,VII,...,14-01-2020,NaN,ACCEPTED,18-04-2020,Active,3203.0,Pune DO,Maharashtra SO,M93,Pune V RSA
3,4.0,133961.0,KTS NAGAMANICKAM CHETTIAR,24-06-2022,11:30:06,Other,24-06-2022,10:59:50,ATOS,VII,...,20-10-2019,04-12-2021 17:41,ACCEPTED,14-12-2019,Active,4104.0,Salem DO,Tamilnadu SO,T25,Namakkal II RSA
4,5.0,270292.0,SARAVANA AGENCIES (LOCK NO.243),24-06-2022,11:30:06,Other,24-06-2022,11:30:00,ATOS,VI,...,07-02-2019,NaN,ACCEPTED,15-09-2020,Active,4103.0,Madurai DO,Tamilnadu SO,T39,Madurai II RSA

In [8]:
df.tail()

,SNo,RO Code,RO Name,Last Data Recvd on (Date),Last Data Recvd on (Time),Last Known Mode of Commn,LAST FCC TRANSACTION DATE,LAST FCC TRANSACTION TIME,Automation Vendor,Phase,...,VSAT INTEGRATION DATE,Last Communication over VSAT,SAT STATUS,SAT DATE,SAP STATUS,Divisional Office,Divisional Office Name,State Office,SalesArea Code,SalesArea Name
33204,33205.0,311522.0,NATIONAL SERVICE STATION ADHOC,20-11-2018,15:24:53,Other,20-11-2018,15:23:47,ATOS,VII,...,NaN,NaN,NOT YET INITIATED,NaN,Terminated,4301.0,Bangalore DO,Karnataka SO,K45,Bangalore IV RSA
33205,33206.0,154827.0,RAMAGANGA AREA DEV.AUTHORITY,02-11-2018,15:32:55,Other,02-11-2018,15:32:38,ATOS,VII,...,NaN,NaN,ACCEPTED,02-09-2019,Powered OFF,1407.0,Kanpur DO,Uttar Pradesh SO,UP1,Kanpur IV RSA
33206,33207.0,123440.0,MADANLAL HARINARAYAN,06-10-2018,15:25:10,Other,06-10-2018,15:25:05,ORPAK,VI,...,NaN,NaN,NOT YET INITIATED,NaN,Active,1301.0,Jaipur DO,Rajasthan SO,R31,Jaipur-IV RSA
33207,33208.0,191577.0,S MUNIRATHNAM NAIDU FILLING STATION,01-09-2018,13:26:20,Other,16-08-2018,20:05:58,ATOS,VI,...,NaN,NaN,NOT YET INITIATED,NaN,Powered OFF,4404.0,TIRUPATI DO,TAPSO,A78,TIRUPATI RSA
33208,33209.0,289373.0,SAYED BROTHERS FILLING STATION,28-06-2018,16:28:12,Other,28-06-2018,16:28:20,ATOS,VI,...,NaN,NaN,ACCEPTED,06-06-2019,Powered OFF,2201.0,Bhubneswar DO,Odisha SO,O10,Fuels-Paradeep(R)

In [10]:
df.shape

(33209, 28)

In [11]:
df.dtypes

SNo                             float64
RO Code                         float64
RO Name                          object
Last Data Recvd on (Date)        object
Last Data Recvd on (Time)        object
Last Known Mode of Commn         object
LAST FCC TRANSACTION DATE        object
LAST FCC TRANSACTION TIME        object
Automation Vendor                object
Phase                            object
BOS Version                      object
FCC Version                      object
SVM Upgrade Date                 object
Date of Initialization           object
VSAT VENDOR                      object
ITPS Vendor 1                    object
ITPS Vendor 2                    object
VSAT INSTALLATION DATE           object
VSAT INTEGRATION DATE            object
Last Communication over VSAT     object
SAT STATUS                       object
SAT DATE                         object
SAP STATUS                       object
Divisional Office               float64
Divisional Office Name           object
State Office                     object
SalesArea Code                   object
SalesArea Name                   object
dtype: object

In [12]:
df.count()

SNo                             33209
RO Code                         33209
RO Name                         33209
Last Data Recvd on (Date)       33209
Last Data Recvd on (Time)       33209
Last Known Mode of Commn        33209
LAST FCC TRANSACTION DATE       33209
LAST FCC TRANSACTION TIME       33209
Automation Vendor               33209
Phase                           33209
BOS Version                     33057
FCC Version                     33059
SVM Upgrade Date                33059
Date of Initialization          32756
VSAT VENDOR                     28104
ITPS Vendor 1                   24984
ITPS Vendor 2                    2294
VSAT INSTALLATION DATE          27845
VSAT INTEGRATION DATE           27185
Last Communication over VSAT    18490
SAT STATUS                      33209
SAT DATE                        32042
SAP STATUS                      33209
Divisional Office               33209
Divisional Office Name          33209
State Office                    33209
SalesArea Code                  33209
SalesArea Name                  33209
dtype: int64